# Generated by Django 5.1.3 on 2025-01-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_employee_team_leader"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
            ],
        ),
    ]
