# Generated by Django 5.1.3 on 2025-01-18 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_teamleader"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_employees",
                to="api.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="employee",
            name="team_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to="api.teamleader",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executed_tasks",
                to="api.employee",
            ),
        ),
    ]
